export const CATEGORIES: Record<string, string[]> = {
  "Mode non-genrée": [
    "Hauts & T-shirts",
    "Bas & Pantalons",
    "Robes & Jupes",
    "Vestes & Manteaux",
    "Lingerie & Sous-vêtements",
    "Maillots de bain",
    "Accessoires mode",
    "Chaussures",
    "Casquettes & Chapeaux",
    "Écharpes & Foulards",
  ],
  "Art & Culture": [
    "Peinture & Dessin",
    "Photographie",
    "Illustration",
    "Sculpture",
    "Art numérique & NFT",
    "Affiches & Prints",
    "Sérigraphie",
    "Broderie & Textile",
    "Céramique",
    "Art queer & Militant",
  ],
  "Bijoux": [
    "Bagues",
    "Colliers & Pendentifs",
    "Boucles d'oreilles",
    "Bracelets",
    "Piercings",
    "Broches & Épingles",
    "Cheveux & Barrettes",
    "Sets & Parures",
  ],
  "Zines & Édition": [
    "Zines",
    "Livres & Romans",
    "BD & Comics",
    "Poésie",
    "Fanzines",
    "Carnets & Journaux",
    "Cartes & Papeterie",
    "Affiches militantes",
  ],
  "Corps & Soin": [
    "Soins visage",
    "Soins corps",
    "Soins cheveux",
    "Parfums & Bougies",
    "Huiles & Sérums",
    "Maquillage",
    "Bien-être & Relaxation",
    "Hygiène naturelle",
  ],
  "Intimité": [
    "Sextoys",
    "Lingerie & Dessous",
    "Lubrifiants & Accessoires",
    "Bien-être intime",
    "Éducation & Ressources",
    "Packaging discret",
  ],
  "Maison": [
    "Décoration murale",
    "Bougies & Diffuseurs",
    "Textile maison",
    "Vaisselle & Cuisine",
    "Plantes & Jardinage",
    "Rangement & Organisation",
    "Lighting & Ambiance",
  ],
  "Services": [
    "Coaching & Accompagnement",
    "Cours en ligne",
    "Consultation",
    "Graphisme & Création",
    "Photo & Vidéo",
    "Traduction & Rédaction",
    "Astro & Tarot",
    "Bien-être & Thérapie",
    "Tatouage & Body art",
  ],
  "Expériences": [
    "Atelier créatif",
    "Cours & Formation",
    "Événement communautaire",
    "Retraite & Séjour",
    "Sortie & Visite",
    "Concert & Spectacle",
    "Rencontre & Speed-dating",
    "Sport & Danse",
  ],
};

export const CATEGORY_LIST = Object.keys(CATEGORIES);

export function getSubcategories(category: string): string[] {
  return CATEGORIES[category] ?? [];
}
