export const categories = [
  { id: 'clothing', name: 'Clothing & Apparel' },
  { id: 'accessories', name: 'Accessories' },
  { id: 'pride-gear', name: 'Pride Gear' },
  { id: 'art', name: 'Art & Prints' },
  { id: 'home-decor', name: 'Home Decor' },
  { id: 'beauty', name: 'Beauty & Personal Care' },
  { id: 'books', name: 'Books & Literature' },
  { id: 'music', name: 'Music & Audio' },
  { id: 'crafts', name: 'Handmade Crafts' },
  { id: 'jewelry', name: 'Jewelry' },
  { id: 'tech', name: 'Tech & Gadgets' },
  { id: 'health', name: 'Health & Wellness' },
  { id: 'toys-games', name: 'Toys & Games' },
  { id: 'pet-supplies', name: 'Pet Supplies' },
  { id: 'stationery', name: 'Stationery & Paper Goods' },
  { id: 'food-drink', name: 'Food & Drink' },
  { id: 'services', name: 'Professional Services' },
  { id: 'education', name: 'Educational Resources' },
  { id: 'events', name: 'Events & Experiences' },
  { id: 'community', name: 'Community Support' },
  { id: 'media', name: 'Media & Entertainment' },
  { id: 'other', name: 'Other' }
];